package com.example.railinfo.data.objects;

import androidx.annotation.NonNull;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.DateFormat;
import java.text.ParseException;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Locale;

/**
 * Defines the structure of a service that's retrieved from the National Rail API
 * <p>
 * Holds the necessary data associated with each service, and has methods to simplify displaying
 * the data to the user within the ServiceHolder.
 *
 * @author Sam Townley
 * @version 1.2
 */
public class ServiceData {

    /** The name of the station the data within this class relates to. */
    private final String station;

    /** The Computer-Reservation System (CRS) code of the station above. */
    private final String crs;

    /** The unique ServiceID generated by the National Rail API for this service. */
    private String id;

    /**
     * An array containing JSONObject's, each representing an origin for the service.
     * A service can have 1 or more origin stations.
     */
    private JSONArray origin;

    /**
     * An array containing JSONObject's, each representing a destination for the service.
     * A service can have 1 or more destination stations.
     */
    private JSONArray destination;

    /**
     * The scheduled arrival of the service at the station defined above.
     * If this service starts here, this attribute will be set to the empty string ("").
     */
    private String scheduled_arr;

    /**
     * The estimated (real-time) arrival of the service at the station defined above.
     * If this service starts here, this attribute will be set to the empty string ("").
     */
    private String estimated_arr;

    /**
     * The scheduled departure of the service at the station defined above.
     * If this service terminates here, this attribute will be set to the empty string ("").
     */
    private String scheduled_dep;

    /**
     * The estimated (real-time) departure of the service at the station defined above.
     * If this service terminates here, this attribute will be set to the empty string ("").
     */
    private String estimated_dep;

    /** The full name of the train operator running the service. */
    private String operator;

    /** A boolean flag representing whether the service has been cancelled at this station. */
    private Boolean cancelled;

    /**
     * The expected platform that the service will arrive/depart at.
     * If the platform is unknown, this will be set to the empty string ("").
     */
    private String platform;

    /**
     * An array containing JSONObject's, each representing a station the service has previously
     * called at. If the service starts here, this will remain as an empty JSONArray.
     */
    private JSONArray previous_calls = new JSONArray();

    /**
     * An array containing JSONObject's, each representing a station the service has yet to
     * call at. If the service terminates here, this will remain as an empty JSONArray.
     */
    private JSONArray future_calls = new JSONArray();

    /** A date and time that the data was fetched from the API. */
    private Date last_refreshed = null;

    /**
     * Constructs a new ServiceData object, providing the name and CRS code of the station that
     * the service information relates to.
     *
     * @param data A JSONObject containing the service data, as fetched from the National Rail API.
     * @param station The name of the station this service relates to.
     * @param crs The CRS of the station this service relates to.
     */
    public ServiceData(JSONObject data, String station, String crs) {
        // Set service attributes from JSON object passed in
        this.station = station;
        this.crs = crs;
        loadData(data);
    }

    /**
     * Constructs a new ServiceData object from just a JSONObject. This constructor should be used
     * by the ServiceInfoActivity when reconstructing a ServiceData object using the JSONObject
     * string returned from ServiceData.toString().
     * <p>
     * If the station and crs code aren't contained in the JSONObject, they will be set as the
     * empty string (""), which will cause issues when rendering the service's journey.
     *
     * @param data A JSONObject containing the service data, as fetched from the National Rail API.
     */
    public ServiceData(JSONObject data) {
        // Set service attributes from JSON object passed in
        station = data.optString("locationName");
        crs = data.optString("crs");
        loadData(data);
    }

    /**
     * Loads the data from the JSONObject into the class attributes. Is called by both constructors
     * since they share this section of code.
     *
     * @param data A JSONObject containing the service data, as fetched from the National Rail API.
     */
    private void loadData(JSONObject data) {
        // Set the class attributes from the JSONObject
        id = data.optString("serviceID");
        origin = data.optJSONArray("origin");
        destination = data.optJSONArray("destination");
        operator = data.optString("operator");
        cancelled = data.optBoolean("isCancelled");
        platform = data.optString("platform");
        scheduled_dep = data.optString("std");
        estimated_dep = data.optString("etd");
        scheduled_arr = data.optString("sta");
        estimated_arr = data.optString("eta");

        // Try to get the date and time the data was generated, catching any errors that occur
        // whilst parsing the data so that last_accessed stays as null.
        DateFormat df = DateFormat.getTimeInstance();
        try {
            last_refreshed = df.parse(data.getString("timestamp"));
        } catch (JSONException | ParseException e) {
            e.printStackTrace();
        }

        // Try to set previous calls JSON array (if the service doesn't start here),
        // catching an error if it occurs so that the attribute gets left as an empty array.
        if (isArrival()) {
            try {
                previous_calls = data.getJSONArray("previousCallingPoints")
                                     .getJSONObject(0)
                                     .getJSONArray("callingPoint");
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

        // Try to set future calls JSON array (if the service doesn't terminate here),
        // catching an error if it occurs so that the attribute gets left as an empty array.
        if (isDeparture()) {
            try {
                future_calls = data.getJSONArray("subsequentCallingPoints")
                                   .getJSONObject(0)
                                   .getJSONArray("callingPoint");
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Constructs a new json string which stores each of the class attributes using the same keys
     * the National Rail API originally uses, so that the data can be re-parsed by passing it back
     * into a ServiceData constructor.
     * <p>
     * Includes the station name and crs code.
     *
     * @return The data stored by this object, represented as a json string.
     */
    @NonNull
    @Override
    public String toString() {
        // Create a new empty JSONObject to store the data
        JSONObject data = new JSONObject();

        try {
            // Put the data into the JSONObject using the same keys as were originally used.
            data.put("serviceID", id);
            data.put("origin", origin);
            data.put("destination", destination);
            data.put("operator", operator);
            data.put("isCancelled", cancelled);
            data.put("platform", platform);
            data.put("std", scheduled_dep);
            data.put("etd", estimated_dep);
            data.put("sta", scheduled_arr);
            data.put("eta", estimated_arr);

            // Include the station name and crs so that they don't have to be passed separately.
            data.put("locationName", station);
            data.put("crs", crs);

            // Include the timestamp the data was generated as a string (if it exists).
            if (last_refreshed != null) {
                DateFormat df = DateFormat.getTimeInstance();
                data.put("timestamp", df.format(last_refreshed));
            }

            // Reconstruct the original layout for the previous and subsequent calling points.
            JSONObject inner_array = new JSONObject().put("callingPoint", previous_calls);
            data.put("previousCallingPoints", new JSONArray().put(inner_array));
            inner_array = new JSONObject().put("callingPoint", future_calls);
            data.put("subsequentCallingPoints", new JSONArray().put(inner_array));

        // Handle any JSONExceptions that occur whilst constructing the JSON object.
        } catch (JSONException e) {
            e.printStackTrace();
        }

        // Convert the JSONObject to a string and return the result.
        return data.toString();
    }

    /**
     * Gets the station name(s) of the origin of the service, formatted as a neat list
     * using commas and an ampersand between the last 2 stations.
     *
     * @return The origin(s) of the service as a string.
     */
    public String getOriginString() {
        // Create a string builder to store the string.
        StringBuilder sb = new StringBuilder();

        // Add each origin station to the string
        int i;
        for (i = 0; i < origin.length(); i++) {
            try {
                JSONObject location = origin.getJSONObject(i);

                // If there are multiple origins, add commas between the stations,
                // or an '&' if it's the second to last station.
                if (origin.length()-i > 1 && i > 0) {
                    sb.append(", ");
                } else if (i > 0) {
                    sb.append(" & ");
                }

                // Append the location name, with the CRS code for the station in brackets
                sb.append(location.optString("locationName"));
                sb.append(" (").append(location.optString("crs")).append(")");

            // Handle any JSONExceptions that occur whilst formatting the string
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        return sb.toString();
    }

    /**
     * Checks whether the service has a via station specified for it's journey.
     *
     * @return True if the service goes via somewhere, otherwise false
     */
    public boolean hasVia() {
        JSONObject dest = destination.optJSONObject(0);
        if (dest != null) {
            return !dest.isNull("via");
        } else {
            return false;
        }
    }

    /**
     * Gets the station name that a service goes via, if one exists.
     * <p>
     * If you're planning on calling this method, you should call hasVia() first to check that
     * this exists, otherwise it will return the empty string ("").
     *
     * @return True if the service goes via somewhere, otherwise false
     */
    public String getVia() {
        try {
            return destination.getJSONObject(0).optString("via");
        } catch (JSONException e) {
            e.printStackTrace();
            return "";
        }
    }

    /**
     * Gets the station name(s) of the destination(s) of the service, formatted as a neat list
     * using commas and an ampersand between the last 2 stations.
     *
     * @return The destination(s) of the service as a string.
     */
    public String getDestinationString() {
        // Create a string builder to store the string.
        StringBuilder sb = new StringBuilder();

        // Add each destination station to the string
        int i;
        for (i = 0; i < destination.length(); i++) {
            try {
                JSONObject location = destination.getJSONObject(i);

                // If there are multiple destinations, add commas between the stations,
                // or an '&' if it's the second to last station.
                if (destination.length() - i > 1 && i > 0) {
                    sb.append(", ");
                } else if (i > 0) {
                    sb.append(" & ");
                }

                // Append the location name, with the CRS code for the station in brackets
                sb.append(location.optString("locationName"));
                sb.append(" (").append(location.optString("crs")).append(")");

            // Handle any JSONExceptions that occur whilst formatting the string
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        return sb.toString();
    }

    /**
     * Checks if the service is an arrival the specified station.
     *
     * @return A boolean representing whether this service is arriving from somewhere else.
     */
    public boolean isArrival() {
        return (!scheduled_arr.equals("") && !estimated_arr.equals(""));
    }

    /**
     * Checks if the service departs the specified station.
     *
     * @return A boolean representing whether this service is departing to somewhere else.
     */
    public boolean isDeparture() {
        return (!scheduled_dep.equals("") && !estimated_dep.equals(""));
    }

    /**
     * Gets the estimated arrival time of the service.
     *
     * @return The estimated arrival time as a string.
     */
    public String getEstimatedArrival() {
        return estimated_arr;
    }

    /**
     * Gets the scheduled arrival time of the service.
     *
     * @return The scheduled arrival time as a string.
     */
    public String getScheduledArrival() {
        return scheduled_arr;
    }

    /**
     * Gets the estimated departure time of the service.
     *
     * @return The estimated departure time as a string.
     */
    public String getEstimatedDeparture() {
        return estimated_dep;
    }

    /**
     * Gets the scheduled departure time of the service.
     *
     * @return The scheduled departure time as a string.
     */
    public String getScheduledDeparture() {
        return scheduled_dep;
    }

    /**
     * Gets the name of the operator of the service.
     *
     * @return The name of the train operating company.
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Gets the platform number as a string.
     * This was N/A can be used if a platform isn't available since some stations have platforms
     * with the number 0 so this could be misleading.
     *
     * @return The platform number as string.
     */
    public String getPlatformString() {
        if (!platform.equals("")) {
            return platform;
        } else {
            return "N/A";
        }
    }

    /**
     * Check if the service has been cancelled at this station.
     *
     * @return True if the service has been cancelled, false otherwise.
     */
    public boolean isCancelled() {
        return cancelled;
    }

    /**
     * Check if the service is due to depart late.
     * If called on a service that terminates, this will always return true.
     *
     * @return True if the service is delayed, false otherwise.
     */
    public boolean isDelayedDeparture() {
        return !estimated_dep.equals("On time");
    }

    /**
     * Check if the service is due to arrive late.
     * If called on a service that starts at this station, this will always return true.
     *
     * @return True if the service is delayed, false otherwise.
     */
    public boolean isDelayedArrival() {
        return !estimated_arr.equals("On time");
    }

    /**
     * Calculates the time to destination, and returns this as a formatted string.
     * <p>
     * If this method is called for a service that terminates, it will return "N/A".
     *
     * @return A string representing the number of hours and minutes till this train reaches
     *         it's destination.
     */
    public String getTimeToDestination() {
        // Check the service has future station calls.
        if (future_calls.length() >= 1) {

            // Get the JSONObject representing the destination station
            JSONObject final_call = future_calls.optJSONObject(future_calls.length()-1);
            if (final_call != null) {
                if (!final_call.isNull("st")) {

                    // Parse the 2 times and calculate the number of minutes between them.
                    String final_time = final_call.optString("st");
                    LocalTime t1 = LocalTime.parse(scheduled_dep);
                    LocalTime t2 = LocalTime.parse(final_time);
                    long minutes = ChronoUnit.MINUTES.between(t1, t2);

                    // If the number of minutes if negative (due to overlapping onto the next day)
                    // Calculate the correct value by adding this the total minutes in a day.
                    if (minutes < 0) {
                        minutes = 60L*24 + minutes;
                    }

                    // Format the minutes into a human-readable string of hours and minutes.
                    if (minutes >= 60) {
                        int hours = Math.toIntExact(minutes / 60);
                        if (Math.toIntExact(minutes - (hours * 60L)) != 0) {
                            return String.format(Locale.getDefault(), "%dh %dm", hours, Math.toIntExact(minutes - (hours * 60L)));
                        } else {
                            return String.format(Locale.getDefault(), "%dh", hours);
                        }
                    } else {
                        return String.format(Locale.getDefault(),"%dm", Math.toIntExact(minutes));
                    }
                }
            }
        }
        return "N/A";
    }

    /**
     * Gets the number of station calls left in the service once it departs.
     *
     * @return The number of subsequent station calls.
     */
    public Integer getStops() {
        return future_calls.length();
    }

    /**
     * Constructs a JSONArray, containing JSONObjects for every station in the service's journey,
     * including the station this service was queried in relation to.
     *
     * @return A JSONArray of station JSONObjects.
     */
    public JSONArray getCallingPoints() {

        // Create an empty JSONArray to store all the calling points.
        JSONArray calling_points = new JSONArray();

        // Copy any previous JSONObjects to the new array
        for (int i=0; i < previous_calls.length(); i++) {
            calling_points.put(previous_calls.optJSONObject(i));
        }

        // Create a new JSONObject for the current station and add it to the array
        JSONObject current = new JSONObject();
        try {
            current.put("locationName", station);
            current.put("crs", crs);
            current.put("isCancelled", cancelled);
            if (isDeparture()) {
                current.put("st", scheduled_dep);
                current.put("et", estimated_dep);
            } else {
                current.put("st", scheduled_arr);
                current.put("et", estimated_arr);
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
        calling_points.put(current);

        // Add any future calling points to the new array
        for (int j=0; j < future_calls.length(); j++) {
            calling_points.put(future_calls.optJSONObject(j));
        }
        return calling_points;
    }

    /**
     * Gets the time the data was generated, as a human readable string.
     *
     * @return The time the data was generated as a string.
     */
    public String getLastRefreshed() {
        if (last_refreshed != null) {
            return (String) android.text.format.DateFormat.format("HH:mm", last_refreshed);
        } else {
            return "N/A";
        }
    }

    /**
     * Checks whether the service is meant to terminate the station this ServiceData object was
     * created in relation to.
     *
     * @return True if the service terminates here, otherwise false.
     * @throws JSONException An error occurred whilst getting the destination CRS code.
     */
    public boolean terminatesHere() throws JSONException {
        String dest_crs = destination.getJSONObject(0).getString("crs");
        return (dest_crs.equals(crs));
    }
}
